name: circuits-env
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - scikit-learn
  - jupyterlab
  - pytorch
  - torchvision
  - pip:
      - transformers
      - matplotlib
      - notebook
